sudo: required
services:
  - docker

before_install:
  - docker build -t mardini0803/node-react-app -f Dockerfile.dev .

script:
  # -- --coverage exits the tests automaticaly
  - docker run mardini0803/node-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "node-react-app"
  env: "NodeReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-101888553113"
  bucket_path: "node-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
